paypal:
  client-id: AeHu0zjZDtQk1MBWhwYNxLSVaOniknRwgYZsqQrFBxI44GHMfcQvaGNqNJa7bVut1D7vpi87JXXoBgJn
  client-secret: EMKwvOBjenhC-7QfdEm2Ni5BoDgds86k-Zms_Cu_QbU7WUfn2YH1ojyrtXKUWZdBftcnJnucR3tKOmHc
  mode: sandbox